// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Quit():Promise<void>;

export function StartNotifications(arg1:number):Promise<void>;

export function StopNotifications():Promise<void>;
