// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartNotifications(arg1) {
  return window['go']['main']['App']['StartNotifications'](arg1);
}

export function StopNotifications() {
  return window['go']['main']['App']['StopNotifications']();
}
